# 250Hz PMW3610 plus lower preferred BLE connection latency.
CONFIG_PMW3610_POLLING_RATE_250=y
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0

